version: "3.8"

services:
  diabetes-progression-predictor:
    image: ghcr.io/tony-nyagah/diabetes-progression-predictor:latest
    build: .
    container_name: diabetes-progression-predictor-app
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    volumes:
      - ./models:/app/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3